services:
  postgres:
    image: postgres:18-alpine
    container_name: mq-postgres
    environment:
      POSTGRES_USER: jewan
      POSTGRES_PASSWORD: jewan
      POSTGRES_DB: mq_database
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: mq-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.2.1-management-alpine
    container_name: mq-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: jewan
      RABBITMQ_DEFAULT_PASS: jewan
    volumes:
      - ./infra/rabbitmq-data:/var/lib/rabbitmq

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.5
    container_name: mq-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.9.5
    container_name: mq-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./infra/kafka-data:/var/lib/kafka/data
