services:
  postgres:
    image: postgres:18-alpine
    container_name: mq-postgres
    environment:
      POSTGRES_USER: jewan
      POSTGRES_PASSWORD: jewan
      POSTGRES_DB: mq_database
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: mq-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.2.1-management-alpine
    container_name: mq-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: jewan
      RABBITMQ_DEFAULT_PASS: jewan
    volumes:
      - ./infra/rabbitmq-data:/var/lib/rabbitmq
