services:
  postgres:
    image: postgres:18-alpine
    container_name: mq-postgres
    environment:
      POSTGRES_USER: jewan
      POSTGRES_PASSWORD: jewan
      POSTGRES_DB: mq_database
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: mq-redis
    ports:
      - "6379:6379"
