version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: mq-postgres
    restart: always
    environment:
      POSTGRES_USER: jewan
      POSTGRES_PASSWORD: jewan
      POSTGRES_DB: mq_database
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres-data:/var/lib/postgresql/data
