spring:
  application:
    name: message-queue-api-server
  mvc:
    async:
      request-timeout: 120000
  datasource:
   url: jdbc:postgresql://localhost:5432/mq_database
   username: jewan
   password: jewan
   driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true

server:
  port: 8080

ocr:
  worker:
    base-url: http://localhost:8000
    predict-path: /predict
    connect-timeout-ms: 5000
    read-timeout-ms: 60000

    nodes:
      - http://localhost:8000
      - http://localhost:8001
      - http://localhost:8002
      - http://localhost:8003